### PR TITLE
Build iup from source code

### PR DESCRIPTION
**Pull request by ivanceras**
I made the same [PR here](https://github.com/dcampbell24/rust-iup-sys/pull/4)

Still experimenting on how to build it on windows with appveyor.

### CODE REVIEW

**Comment by cybergeek94** [comment]
As promising as IUP is, I'm unfortunately not interested in continuing to use it in KISS-UI. I'd much prefer to have a backend that is as much pure Rust as possible, so we don't have to download and build third-party dependencies like this. And also the fact that there's just some design choices in IUP that I don't particularly agree with.

`rust-iup-sys` is probably the more appropriate crate for this code anyways, since it links directly with IUP, so I'll punt this to the other guys.

Thanks for the hard work though! I'm sure they'll appreciate it.

**Comment by ivanceras** [comment]
>I'd much prefer to have a backend that is as much pure Rust as possible

Any recommendation project that you are using? I might as well use it.

**Comment by cybergeek94** [comment]
If you want to wait, or even maybe help, I'm starting work on a rewrite of KISS-UI that uses pure Rust and first-party FFI where available (Win32 APIs on Windows, GTK+ on Linux, Cocoa on OS X [if possible]). It's still in its infancy but I'm going to be picking up the pace on it right directly because I'm seeing a strong desire for a good, portable GUI toolkit for Rust.

If you're impatient, [gtk-rs](https://github.com/gtk-rs/gtk) is pretty far along already and doesn't need any external dependencies on platforms with GTK+ already installed (like most Linux distros). I'll be implementing the Linux KISS-UI backend on top of it so I don't have to reinvent the wheel in that respect. It's not the *best* choice for crossplatform, as it's a pain to install on Windows and "looks like shit" on OS X (or so I'm told), but it's not a bad place to start if Linux is your primary target.

**Comment by ivanceras** [comment]
Hi,
I'm looking on these 3 github projects.

* [winapi-rs](https://github.com/retep998/winapi-rs) truely native windows,
* [cocoa-rs](https://github.com/servo/cocoa-rs) truely native mac
* and of course [gtk-rs](https://github.com/gtk-rs/gtk) truely native gnome


We could create a least common denominator widgets for these 3 native libraries, then we can have a rust widget API that is native to each corresponding platforms.

### Notable notes:
* winapi-rs - still needs more rust-wrapping on the widgets
* cocoa-rs - servo focuses only on what they need, that is the window and some menu
* gtk-rs - complete api on most, if not all widgets.

If you have started working on these, then I can find some areas where I can help.

**Comment by cybergeek94** [comment]
That is actually my plan. For the Windows side I'm building a safe abstraction on top of winapi here: https://github.com/cybergeek94/wingui

I debated just rolling this code into the KISS-UI Windows backend since WinGUI would be mostly redundant, but having it as a separate crate means more parallelism in builds as well as separation of concerns (we could say that KISS-UI is written in entirely safe Rust, because all the unsafe stuff is in other crates).

After that, it is a matter of condensing the feature set down to something concise and useful that can be supported across all backends: windows, common widgets such as textboxes, buttons, dropdowns, radio-buttons, etc., image rendering (important for [my personal use-case](https://github.com/cybergeek94/img-dup)), and canvas drawing (OpenGL and native).

OS integration will also be a key feature. I eventually want to support things like dragging and dropping files directly into applications.

**Pull request closed without merging**
